console.log(Boolean(5>4));
console.log(Boolean("ананас">"яблоко"));
console.log(Boolean("2">"12"));
console.log(Boolean(undefined==null));
console.log(Boolean(undefined===null));
console.log(Boolean(null=="\n0\n"));
console.log(Boolean(null===+"\n0\n"));
console.log(""+1+0);
console.log(""-1+0);
console.log(true+false);
console.log(6/"3");
console.log("2"*"3");
console.log(4+5+"px");
console.log("$"+4+5);
console.log("4"-2);
console.log(7/0);
console.log(" -9 "+5);
console.log(" -9 "-5);
console.log(null+1);
console.log(undefined+1);
console.log("\t\n"-2);